const icon=(name)=>({
  home:'<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9M9 20v-7h6v7"/></svg>',
  film:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="m10 9 5 3-5 3zM7 4v3m5-3v3m5-3v3M7 17v3m5-3v3m5-3v3"/></svg>',
  image:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/></svg>',
  wave:'<svg viewBox="0 0 24 24"><path d="M2 10v4m4-8v12m4-15v18m4-13v8m4-12v16m4-11v6"/></svg>',
  folder:'<svg viewBox="0 0 24 24"><path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>',
  bell:'<svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9m-8 12h4"/></svg>',
  plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
  sparkle:'<svg viewBox="0 0 24 24"><path d="m12 3 1.9 5.8L20 11l-6.1 2.2L12 19l-1.9-5.8L4 11l6.1-2.2L12 3Z"/><path d="m19 14 .9 2.1L22 17l-2.1.9L19 20l-.9-2.1L16 17l2.1-.9L19 14Z"/></svg>',
  upload:'<svg viewBox="0 0 24 24"><path d="M12 16V4m-4 4 4-4 4 4"/><path d="M4 16v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3"/></svg>',
  wand:'<svg viewBox="0 0 24 24"><path d="m15 4 5 5M4 20l11-11m-3-7 .7 2.3L15 5l-2.3.7L12 8l-.7-2.3L9 5l2.3-.7L12 3Zm8 11 .6 1.8L22 16l-1.4.5L20 18l-.6-1.5L18 16l1.4-.5L20 14Z"/></svg>',
  play:'<svg viewBox="0 0 24 24"><path d="m8 5 12 7-12 7z"/></svg>',
  check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',
  clock:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',
  download:'<svg viewBox="0 0 24 24"><path d="M12 4v11m-4-4 4 4 4-4"/><path d="M5 20h14"/></svg>',
  refresh:'<svg viewBox="0 0 24 24"><path d="M20 7v5h-5M4 17v-5h5"/><path d="M5.6 9a7 7 0 0 1 11.6-2L20 12M4 12l2.8 5a7 7 0 0 0 11.6-2"/></svg>',
  sound:'<svg viewBox="0 0 24 24"><path d="M11 5 6 9H3v6h3l5 4z"/><path d="M15 9a5 5 0 0 1 0 6m3-9a9 9 0 0 1 0 12"/></svg>',
  mute:'<svg viewBox="0 0 24 24"><path d="M11 5 6 9H3v6h3l5 4zM16 9l5 6m0-6-5 6"/></svg>'
})[name]||'';
const faDigits=s=>String(s).replace(/[0-9]/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=new Intl.DateTimeFormat('fa-IR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
let currentPage='home',mode='text',pickedStyle='سینمایی',currentFilter='همه',toastTimer,lastGeneratedUrl=null,lastGeneratedType=null,lastGeneratedName='';
let projects=[
 {title:'آخرین ایستگاه ماه',duration:'۰۸:۲۴',date:'امروز، ۱۰:۴۲',status:'آماده',kind:'ویدیو',art:'landscape'},
 {title:'قصه‌ی جنگل مه‌آلود',duration:'۱۲:۱۰',date:'دیروز',status:'آماده',kind:'ویدیو',art:'forest'},
 {title:'پرتره در نور نئون',duration:'—',date:'۲ روز پیش',status:'آماده',kind:'تصویر',art:'neon'},
 {title:'صدای باران در کافه',duration:'۰۲:۱۸',date:'۳ روز پیش',status:'آماده',kind:'صوت',art:'audio'}
];
const pageNames={home:'خانه',create:'ساخت ویدیو',images:'تصویرساز',audio:'صدا و گویندگی',library:'پروژه‌های من'};
const pageContent=document.getElementById('page-content');
function projectCard(p,i){
 const artStyles={forest:'linear-gradient(135deg,#183837,#6a8e69 45%,#d6b391)',neon:'linear-gradient(135deg,#22124e,#ce438d 54%,#ff9c6d)',audio:'linear-gradient(135deg,#34243f,#bd7867 50%,#f3c894)'};
 const safeTitle=escapeHtml(p.title);
 const art=p.art==='landscape'?`<img src="/assets/cinematic-landscape.jpg" alt="نمایی از پروژه ${safeTitle}">`:`<div class="abstract-art" style="background:${artStyles[p.art]||artStyles.forest}"></div>`;
 return `<article class="project-card" data-project="${safeTitle}"><div class="project-thumb">${art}<span class="project-type">${icon(p.kind==='تصویر'?'image':p.kind==='صوت'?'wave':'film')}</span><span class="project-time">${p.duration}</span></div><div class="project-info"><h4>${safeTitle}</h4><div class="project-meta"><span>${p.date}</span><span class="project-status"><i class="status-dot"></i>${p.status}</span></div></div></article>`;
}
function toolCard(type,title,copy,style,ico){return `<button class="tool-card" data-page="${type}"><span class="tool-icon ${style}">${icon(ico)}</span><span class="tool-copy"><strong>${title}</strong><small>${copy}</small></span><span class="tool-arrow">←</span></button>`}
function renderHome(){
 return `<div class="welcome-row"><div><h1>سلام سارا، وقت ساختنه ✨</h1><p>ایده‌ات رو وارد کن و بذار Deisa بقیه‌ی مسیر رو برات بسازه.</p></div><div class="welcome-date"><i class="date-dot"></i>${dateLabel}</div></div>
 <section class="hero-card"><div class="hero-art"></div><div class="hero-copy"><span class="eyebrow"><span class="sparkle">✦</span> استودیوی خلاقیت هوش مصنوعی</span><h2>از یک ایده تا یک <span>کلیپ سینمایی</span></h2><p>ایده یا تصویرت را به مدل وصل‌شده بده و کلیپ واقعی بگیر. طول خروجی به مدل، workflow و سخت‌افزار بستگی دارد.</p><div class="hero-actions"><button class="primary-btn" data-page="create">${icon('sparkle')} شروع ساخت ویدیو</button><button class="text-btn" data-page="images">اول تصویر بساز ←</button></div></div><div class="hero-preview"><span class="preview-play">▶</span><span class="preview-details"><strong>آخرین ایستگاه ماه</strong><small>پیش‌نمایش پروژه · ۰۸:۲۴</small></span><span class="hero-sound">♫</span></div></section>
 <section><div class="section-heading"><h3>پروژه‌های اخیر <small>ادامه‌ی کارهات</small></h3><button class="view-all" data-page="library">مشاهده‌ی همه ←</button></div><div class="project-grid">${projects.slice(0,4).map(projectCard).join('')}</div></section>
 <section class="tools-section"><div class="section-heading"><h3>ابزارهای خلاقانه</h3><span class="view-all">همه‌چیز برای ساختن</span></div><div class="tool-grid">${toolCard('create','کلیپ ویدیویی','ساخت کلیپ با مدل خودت','purple','film')}${toolCard('images','تولید تصویر','تصویرسازی با توضیحات متنی','peach','image')}${toolCard('audio','صدا و گویندگی','تبدیل متن به گفتار طبیعی','mint','wave')}</div></section>`;
}
function renderCreate(){
 const imageMode=mode==='image';
 return `<div class="page-heading"><div><h1>ساخت کلیپ ویدیویی</h1><p>مدل‌های ویدیویی معمولاً کلیپ کوتاه می‌سازند؛ طول و خروجی نهایی به مدل و workflow شما بستگی دارد.</p></div><button class="provider-settings" data-action="connection-settings">⚙ اتصال سرویس‌ها</button></div>
 <div class="studio-grid"><section class="form-panel"><div class="field-block"><div class="field-title"><strong>از کجا شروع کنیم؟</strong><small>روش ورودی رو انتخاب کن</small></div><div class="mode-toggle"><button class="mode-option ${!imageMode?'selected':''}" data-mode="text">${icon('film')} نوشتن ایده</button><button class="mode-option ${imageMode?'selected':''}" data-mode="image">${icon('image')} شروع از تصویر</button></div></div>
 <div class="field-block"><div class="field-title"><label for="video-prompt">${imageMode?'توضیح تصویر و داستان':'داستان یا ایده‌ی ویدیو'}</label><small class="optional">هرچه جزئی‌تر، بهتر</small></div><textarea id="video-prompt" class="prompt-input" maxlength="1200" placeholder="${imageMode?'این تصویر را به یک روایت سینمایی تبدیل کن؛ چه اتفاقی می‌افتد، چه حسی دارد و پایانش چطور است؟':'مثلاً: داستان یک فضانورد را روایت کن که بعد از سال‌ها به زمین برمی‌گردد و می‌فهمد زمان برای همه متوقف شده است...'}"></textarea><div class="prompt-foot"><button class="prompt-boost" data-action="boost">${icon('sparkle')} بهترش کن</button><span class="char-count">۰ / ۱۲۰۰</span></div></div>
 ${imageMode?`<div class="field-block"><div class="field-title"><label>تصویر مرجع</label><small>یک تصویر برای الهام بارگذاری کن</small></div><label class="upload-zone" for="reference-file"><span class="upload-symbol">${icon('upload')}</span><span class="upload-copy"><strong class="upload-label">تصویرت را اینجا رها کن یا انتخاب کن</strong><small>PNG یا JPG · حداکثر ۱۵ مگابایت</small></span><span class="upload-action">انتخاب فایل</span><img class="upload-preview" alt="پیش‌نمایش تصویر انتخاب‌شده"><input type="file" id="reference-file" accept="image/*" hidden></label></div>`:''}
 <div class="form-divider"></div><div class="form-row"><div class="field-block"><div class="field-title"><label>موتور تولید ویدیو</label><small>مدت کلیپ تابع مدل است</small></div><div class="engine-note">ComfyUI خودمیزبان · بدون سهمیه‌ی API؛ نیازمند GPU و workflow ویدیویی</div></div><div class="field-block"><div class="field-title"><label for="format-select">نسبت تصویر</label></div><select id="format-select" class="field-select"><option>افقی ۱۶:۹ · یوتیوب</option><option>عمودی ۹:۱۶ · ریلز</option><option>مربع ۱:۱ · شبکه‌های اجتماعی</option></select></div></div>
 <div class="form-row"><div class="field-block"><div class="field-title"><label>سبک بصری</label><small>یک حال‌وهوا انتخاب کن</small></div><div class="style-chips">${['سینمایی','انیمه','مستند','فانتزی','مینیمال'].map(s=>`<button class="style-chip ${pickedStyle===s?'selected':''}" data-style="${s}">${s}</button>`).join('')}</div></div><div class="field-block"><div class="field-title"><label for="voice-select">راوی و موسیقی</label></div><select id="voice-select" class="field-select"><option>بدون راوی · فقط موسیقی</option><option>آوا · زنانه و آرام</option><option>آرمان · مردانه و گرم</option><option>روایتگر مستند</option></select></div></div>
 <div class="generate-row"><button class="primary-btn generate-btn" data-generate="video">${icon('sparkle')} تولید کلیپ واقعی</button><span class="generate-note">برای کلیپ‌های بلند باید چند خروجی را جداگانه بسازید و تدوین کنید.</span></div></section>
 <aside class="preview-panel"><div class="preview-header"><strong>پیش‌نمایش خروجی</strong><button class="provider-settings compact" data-action="connection-settings">تنظیم اتصال</button></div><div class="studio-poster"><img src="/assets/cinematic-landscape.jpg" alt="نمونه‌ی تصویری"><span class="poster-center">▶</span><span class="poster-caption"><strong class="poster-title">پیش‌نمایش نمونه</strong><small>خروجی واقعی پس از اتصال سرویس</small></span></div><div class="preview-facts"><div class="fact"><small>مدت</small><strong class="fact-duration">وابسته به مدل</strong></div><div class="fact"><small>نوع خروجی</small><strong class="fact-scenes">یک کلیپ</strong></div><div class="fact"><small>سبک بصری</small><strong class="fact-style">سینمایی</strong></div></div><div class="timeline-title">درباره‌ی تولید <span>اطلاعات سرویس</span></div><div class="preview-foot">${icon('clock')} رندر روی ComfyUI به GPU، حافظه و workflow نصب‌شده نیاز دارد.</div></aside></div>`;
}
function renderImages(){return `<div class="page-heading"><div><h1>تصویرساز هوشمند</h1><p>مدل‌های محلی و ابری را انتخاب کن؛ سهمیه‌ی سرویس ابری محدود است.</p></div><button class="provider-settings" data-action="connection-settings">⚙ اتصال سرویس‌ها</button></div><div class="generator-layout"><section class="generator-form"><div class="field-block"><div class="field-title"><label for="image-prompt">چه تصویری در ذهنته؟</label><small>توصیف رو فارسی یا انگلیسی بنویس</small></div><textarea id="image-prompt" class="prompt-input" maxlength="800" placeholder="مثلاً: یک کتابخانه‌ی قدیمی در دل جنگل، نور طلایی از پنجره می‌تابد، حس جادویی و سینمایی، جزئیات زیاد..."></textarea><div class="prompt-foot"><button class="prompt-boost" data-action="boost">${icon('sparkle')} بهترش کن</button><span class="char-count">۰ / ۸۰۰</span></div></div><div class="form-row"><div class="field-block"><div class="field-title"><label>سبک تصویر</label></div><select id="image-style" class="field-select"><option>سینمایی و واقع‌گرا</option><option>تصویرسازی دیجیتال</option><option>آبرنگ</option><option>انیمه</option><option>سه‌بعدی</option></select></div><div class="field-block"><div class="field-title"><label for="image-provider">موتور تصویر</label></div><select id="image-provider" class="field-select"><option value="comfyui">ComfyUI روی سخت‌افزار خودم · بدون سهمیه‌ی API</option><option value="huggingface">Hugging Face · اعتبار رایگان محدود</option></select></div></div><div class="field-block"><div class="field-title"><label>اندازه‌ی تصویر</label></div><select id="image-size" class="field-select"><option value="1024x1024">مربع · ۱۰۲۴ × ۱۰۲۴</option><option value="1024x1440">عمودی · ۱۰۲۴ × ۱۴۴۰</option><option value="1440x1024">افقی · ۱۴۴۰ × ۱۰۲۴</option></select></div><div class="generate-row"><button class="primary-btn generate-btn" data-generate="image">${icon('sparkle')} تولید تصویر واقعی</button><span class="generate-note">تولید فقط پس از پیکربندی backend انجام می‌شود.</span></div></section><section class="image-result" id="image-result"><div class="result-empty"><span class="empty-icon">${icon('image')}</span><strong>اینجا تصویرت رو می‌بینی</strong><p>یک مدل را وصل کن و prompt را بفرست تا تصویر واقعی تولید شود.</p></div></section></div>`}
function renderAudio(){return `<div class="page-heading"><div><h1>صدا و گویندگی</h1><p>متنت رو به صدای طبیعی تبدیل کن یا برای ویدیوت گوینده انتخاب کن.</p></div><button class="provider-settings" data-action="connection-settings">تنظیمات سرویس‌ها</button></div><div class="audio-layout"><section class="generator-form"><div class="field-block"><div class="field-title"><label for="audio-text">متنی که باید خوانده شود</label><small>حداکثر ۵۰۰۰ نویسه</small></div><textarea id="audio-text" class="prompt-input" maxlength="5000" placeholder="متنت رو اینجا بنویس... مثلاً: گاهی یک سفر، فقط برای پیدا کردن راه خانه آغاز می‌شود."></textarea><div class="prompt-foot"><span>زبان خروجی: فارسی</span><span class="char-count">۰ / ۵۰۰۰</span></div></div><div class="field-block"><div class="field-title"><strong>انتخاب صدا</strong><button class="prompt-boost" data-action="voices">شنیدن نمونه صدا</button></div><div class="voice-card"><span class="voice-avatar">آ</span><span class="voice-data"><strong>آوا · زنانه</strong><small>آرام، گرم و داستان‌گو</small></span><button class="voice-select" data-action="voice-select">تغییر صدا⌄</button></div></div><div class="form-row"><div class="field-block"><div class="field-title"><label>حس و لحن</label></div><select class="field-select"><option>طبیعی و صمیمی</option><option>روایت سینمایی</option><option>انرژی‌بخش</option><option>آرام و مراقبه‌ای</option></select></div><div class="field-block"><div class="field-title"><label>سرعت گفتار</label><small>۱٫۰×</small></div><div class="duration-control"><input class="range speed-range" type="range" min="70" max="130" value="100" style="--range:50%"><div class="range-labels"><span>آرام</span><span>سریع</span></div></div></div></div><div class="generate-row"><button class="secondary-btn generate-btn" data-generate="audio" disabled>${icon('wave')} تولید صوت هنوز متصل نیست</button><span class="generate-note">در حال حاضر اتصال واقعی فقط برای تصویر و ویدیو آماده است.</span></div></section><aside class="audio-empty" id="audio-result"><div class="result-empty"><span class="empty-icon">${icon('wave')}</span><strong>صدات اینجا آماده می‌شه</strong><p>یک متن وارد کن، راوی رو انتخاب کن و نمونه‌ی گفتار رو بساز.</p></div></aside></div>`}
function renderLibrary(){const filtered=currentFilter==='همه'?projects:projects.filter(p=>p.kind===currentFilter);return `<div class="page-heading"><div><h1>پروژه‌های من</h1><p>ویدیوها، تصویرها و صداهایی که با Deisa ساختی.</p></div><button class="primary-btn" data-page="create">${icon('plus')} پروژه‌ی جدید</button></div><div class="library-toolbar">${['همه','ویدیو','تصویر','صوت'].map(f=>`<button class="filter-btn ${currentFilter===f?'selected':''}" data-filter="${f}">${f}</button>`).join('')}<input class="search" id="library-search" placeholder="جست‌وجوی پروژه‌ها..." aria-label="جست‌وجوی پروژه‌ها"></div><div class="project-grid library-grid">${filtered.length?filtered.map(projectCard).join(''):`<div class="empty-state"><span>${icon('folder')}</span><strong>پروژه‌ای اینجا نیست</strong><p>فیلتر دیگری رو امتحان کن یا یک پروژه‌ی تازه بساز.</p></div>`}</div>`}
function render(){pageContent.innerHTML=({home:renderHome,create:renderCreate,images:renderImages,audio:renderAudio,library:renderLibrary}[currentPage]||renderHome)();document.getElementById('crumb-current').textContent=pageNames[currentPage]||'خانه';document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===currentPage));if(currentPage==='create'){updateStudioTitle();if(lastGeneratedType==='video'&&lastGeneratedUrl)showGeneratedVideo(lastGeneratedUrl)}if(currentPage==='images'&&lastGeneratedType==='image'&&lastGeneratedUrl)showGeneratedImage(lastGeneratedUrl);}
function updateStudioTitle(){const input=document.getElementById('video-prompt');const title=document.querySelector('.poster-title');if(input&&title){const raw=input.value.trim();title.textContent=raw?raw.slice(0,31)+(raw.length>31?'…':''):'ایستگاهِ پایانِ زمین';}}
function showToast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
function showModal(title,copy){document.getElementById('modal-title').textContent=title;document.getElementById('modal-copy').textContent=copy;document.getElementById('modal-extra').innerHTML='';document.getElementById('modal-backdrop').classList.add('open');document.getElementById('modal-backdrop').setAttribute('aria-hidden','false')}
function hideModal(){document.getElementById('modal-backdrop').classList.remove('open');document.getElementById('modal-backdrop').setAttribute('aria-hidden','true')}
function setPage(page){if(!pageNames[page])return;currentPage=page;render();window.scrollTo({top:0,behavior:'smooth'})}
function gatewayConfig(){
 const fallbackOrigin=(location.protocol==='http:'||location.protocol==='https:')&&location.hostname!=='appassets.androidplatform.net'?location.origin:'';
 const base=(localStorage.getItem('deisa_api_base')||window.DEISA_API_BASE_URL||fallbackOrigin).trim().replace(/\/$/,'');
 return {base,key:localStorage.getItem('deisa_api_key')||''};
}
function apiHeaders(json=false){const c=gatewayConfig();return {...(json?{'Content-Type':'application/json'}:{}),...(c.key?{Authorization:`Bearer ${c.key}`}:{})}}
function openConnectionSettings(){
 const config=gatewayConfig();
 showModal('اتصال سرویس‌های هوش مصنوعی','آدرس backend و کلید دسترسی را وارد کن. کلید مدل‌های Hugging Face یا ComfyUI باید روی سرور بماند و داخل برنامه قرار نگیرد.');
 document.getElementById('modal-extra').innerHTML=`<div class="connection-form"><label for="gateway-url">آدرس API Deisa</label><input id="gateway-url" class="field-input" type="url" placeholder="https://your-server.example" value="${escapeHtml(config.base)}"><label for="gateway-key">کلید دسترسی backend (در صورت نیاز)</label><input id="gateway-key" class="field-input" type="password" autocomplete="off" placeholder="کلید تنظیم‌شده در سرور" value="${escapeHtml(config.key)}"><div class="connection-actions"><button class="primary-btn" data-action="save-connection">ذخیره</button><button class="secondary-btn" data-action="test-connection">آزمایش اتصال</button></div><div class="connection-status" id="connection-status" aria-live="polite"></div><small>برای اندروید باید سرور در اینترنت و با HTTPS در دسترس باشد. محدودیت رایگان ابری نامحدود نیست.</small></div>`;
}
async function testConnection(){
 const status=document.getElementById('connection-status');const base=(document.getElementById('gateway-url')?.value||'').trim().replace(/\/$/,'');
 if(!base){status.textContent='ابتدا آدرس API را وارد کنید.';return}
 status.textContent='در حال بررسی…';
 try{const pendingKey=document.getElementById('gateway-key')?.value.trim();const headers=pendingKey?{Authorization:`Bearer ${pendingKey}`} : apiHeaders();const response=await fetch(base+'/api/providers',{headers});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();const p=data.providers||{};status.textContent=`وصل شد · Hugging Face: ${p.huggingface?'آماده':'تنظیم‌نشده'} · ComfyUI تصویر: ${p.comfyui?'آماده':'تنظیم‌نشده'} · ComfyUI ویدیو: ${p.comfyuiVideo?'آماده':'تنظیم‌نشده'}`;}
 catch(error){status.textContent=`اتصال ناموفق: ${error.message}. آدرس، HTTPS و CORS را بررسی کنید.`}
}
function saveConnection(){
 const base=(document.getElementById('gateway-url')?.value||'').trim().replace(/\/$/,'');const key=(document.getElementById('gateway-key')?.value||'').trim();
 if(base&&!/^https?:\/\//i.test(base)){showToast('آدرس باید با https:// یا http:// شروع شود.');return}
 if(base)localStorage.setItem('deisa_api_base',base);else localStorage.removeItem('deisa_api_base');
 if(key)localStorage.setItem('deisa_api_key',key);else localStorage.removeItem('deisa_api_key');
 showToast('تنظیمات اتصال روی همین دستگاه ذخیره شد.');testConnection();
}
function fileAsDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('خواندن تصویر مرجع ناموفق بود.'));reader.readAsDataURL(file)})}
function downloadGenerated(){if(!lastGeneratedUrl)return;const a=document.createElement('a');a.href=lastGeneratedUrl;a.download=lastGeneratedName|| (lastGeneratedType==='video'?'deisa-video.mp4':'deisa-image.png');document.body.appendChild(a);a.click();a.remove()}
function showGeneratedImage(url){const panel=document.getElementById('image-result');if(!panel)return;panel.classList.add('has-image');panel.innerHTML=`<img class="generated-art" src="${url}" alt="تصویر تولیدشده"><div class="image-result-actions"><button data-action="download">${icon('download')} ذخیره‌ی تصویر</button><button data-action="regenerate">${icon('refresh')} ساخت دوباره</button></div><span class="demo-badge live-badge">تولید واقعی</span>`}
function showGeneratedVideo(url){const poster=document.querySelector('.studio-poster');if(!poster)return;poster.innerHTML=`<video class="generated-video" controls playsinline autoplay src="${url}">پخش ویدیو در مرورگر پشتیبانی نمی‌شود.</video>`;const facts=document.querySelector('.preview-facts');if(facts)facts.innerHTML='<div class="fact"><small>وضعیت</small><strong>آماده</strong></div><div class="fact"><small>خروجی</small><strong>کلیپ ویدیویی</strong></div><div class="fact"><small>فایل</small><button class="inline-download" data-action="download">ذخیره</button></div>'}
async function startGeneration(type,button){
 const input=type==='video'?document.getElementById('video-prompt'):type==='image'?document.getElementById('image-prompt'):document.getElementById('audio-text');
 if(!input||!input.value.trim()){input?.focus();showToast(type==='video'?'اول ایده‌ی ویدیوت رو بنویس.':'اول متن یا توضیحت رو وارد کن.');return}
 if(type==='audio'){showModal('تولید گفتار هنوز وصل نیست','این درخواست روی تصویر و ویدیو متمرکز است؛ تولید صوت به سرویس جداگانه نیاز دارد.');return}
 const provider=document.getElementById(type==='video'?'video-provider':'image-provider')?.value||'comfyui';
 const reference=document.getElementById('reference-file')?.files?.[0];
 if(type==='video'&&mode==='image'&&!reference){showToast('برای شروع از تصویر، یک تصویر مرجع انتخاب کن.');return}
 if(type==='video'&&provider==='huggingface'&&reference){showModal('ورودی تصویر پشتیبانی نمی‌شود','مدل Hugging Face این اتصال در حالت text-to-video است. برای image-to-video از workflow مناسب ComfyUI استفاده کنید.');return}
 if(reference&&reference.size>15*1024*1024){showToast('تصویر مرجع باید کمتر از ۱۵ مگابایت باشد.');return}
 const config=gatewayConfig();if(!config.base){openConnectionSettings();return}
 const old=button.innerHTML;button.disabled=true;button.classList.add('is-loading');button.innerHTML='<span class="spinner"></span> در حال تولید با مدل واقعی…';
 try{
   let prompt=input.value.trim();const style=type==='image'?document.getElementById('image-style')?.value:pickedStyle;if(style)prompt+=`\nVisual style: ${style}`;
   const options={};
   if(type==='image'){const [width,height]=(document.getElementById('image-size')?.value||'1024x1024').split('x').map(Number);options.width=width;options.height=height;}
   if(reference){options.referenceImage=await fileAsDataUrl(reference);options.referenceName=reference.name;}
   const response=await fetch(config.base+'/api/generate',{method:'POST',headers:apiHeaders(true),body:JSON.stringify({kind:type,provider,prompt,options})});
   if(!response.ok){let message=`HTTP ${response.status}`;try{const err=await response.json();message=err.error||message}catch{}throw new Error(message)}
   const blob=await response.blob();const url=URL.createObjectURL(blob);if(lastGeneratedUrl)URL.revokeObjectURL(lastGeneratedUrl);lastGeneratedUrl=url;lastGeneratedType=type;lastGeneratedName=response.headers.get('X-Deisa-Filename')||'';
   if(type==='image'){showGeneratedImage(url);showToast('تصویر با موفقیت تولید شد.');}
   else{showGeneratedVideo(url);const title=input.value.trim();projects.unshift({title:title.slice(0,30)+(title.length>30?'…':''),duration:'کلیپ',date:'همین حالا',status:'آماده',kind:'ویدیو',art:'landscape',mediaUrl:url});showToast('کلیپ واقعی آماده‌ی پخش و دانلود است.');}
 }catch(error){showModal('تولید انجام نشد',`${error.message}\n\nتنظیمات backend، مدل/workflow، اعتبار سرویس و وضعیت GPU را بررسی کنید.`)}
 finally{button.disabled=false;button.innerHTML=old;button.classList.remove('is-loading')}
}
document.addEventListener('click',e=>{
 const page=e.target.closest('[data-page]');if(page){e.preventDefault();setPage(page.dataset.page);return}
 const modeBtn=e.target.closest('[data-mode]');if(modeBtn){mode=modeBtn.dataset.mode;render();return}
 const style=e.target.closest('[data-style]');if(style){pickedStyle=style.dataset.style;document.querySelectorAll('.style-chip[data-style]').forEach(c=>c.classList.toggle('selected',c===style));const fs=document.querySelector('.fact-style');if(fs)fs.textContent=pickedStyle;return}
 const filter=e.target.closest('[data-filter]');if(filter){currentFilter=filter.dataset.filter;render();return}
 const action=e.target.closest('[data-action]')?.dataset.action;if(action){if(action==='close-modal')hideModal();else if(action==='connection-settings')openConnectionSettings();else if(action==='save-connection')saveConnection();else if(action==='test-connection')testConnection();else if(action==='upgrade')showModal('Deisa حرفه‌ای','پلن حرفه‌ای در نسخه‌ی بعدی فعال می‌شود. در آن نسخه، اعتبار بیشتر و امکانات بیشتر در دسترس خواهند بود.');else if(action==='help')showModal('راهنمای Deisa','برای تولید واقعی، ابتدا backend را در «اتصال سرویس‌ها» تنظیم کنید. ComfyUI روی سخت‌افزار خودتان سهمیه‌ی API ندارد اما GPU و برق لازم دارد؛ Hugging Face اعتبار رایگان محدود دارد.');else if(action==='notifications')showToast('اعلان تازه‌ای نداری.');else if(action==='boost'){const prompt=document.querySelector('.prompt-input');if(prompt){prompt.value=prompt.value.trim()?prompt.value+'، با جزئیات بصری دقیق، نورپردازی سینمایی و روایت منسجم':'یک داستان کوتاه سینمایی با شروعی گیرا، شخصیت‌پردازی عمیق، صحنه‌های پرجزئیات و پایانی به‌یادماندنی';prompt.dispatchEvent(new Event('input',{bubbles:true}));showToast('ایده‌ات برای یک خروجی دقیق‌تر گسترش پیدا کرد.')} }else if(action==='voices')showModal('نمونه‌ی صدا','در نسخه‌ی متصل می‌توانی صدای راوی را پیش از انتخاب بشنوی.');else if(action==='voice-select')showModal('انتخاب گوینده','آوا · زنانه و آرام   |   آرمان · مردانه و گرم   |   روایتگر مستند');else if(action==='download')downloadGenerated();else if(action==='regenerate'){const b=document.querySelector('[data-generate="image"]');if(b)startGeneration('image',b);}else if(action==='play-audio'){const b=e.target.closest('[data-action="play-audio"]');b.classList.toggle('playing');b.innerHTML=b.classList.contains('playing')?'Ⅱ':icon('play');showToast('پخش صوت در نسخه‌ی نمایشی غیرفعال است.')}return}
 const generate=e.target.closest('[data-generate]');if(generate){startGeneration(generate.dataset.generate,generate);return}
 const chip=e.target.closest('.style-chip:not([data-style])');if(chip){chip.parentElement.querySelectorAll('.style-chip').forEach(c=>c.classList.toggle('selected',c===chip));return}
 const card=e.target.closest('.project-card');if(card){showModal(card.dataset.project,'این کارت یک پروژه‌ی نمایشی است. با اتصال فضای ذخیره‌سازی، جزئیات و فایل اصلی اینجا باز می‌شوند.');return}
});
document.addEventListener('input',e=>{
 if(e.target.matches('.prompt-input')){const count=e.target.closest('.field-block')?.querySelector('.char-count');if(count)count.textContent=`${faDigits(e.target.value.length)} / ${faDigits(e.target.maxLength)}`;if(e.target.id==='video-prompt')updateStudioTitle();}
 if(e.target.id==='library-search'){const q=e.target.value.toLowerCase();document.querySelectorAll('.library-grid .project-card').forEach(card=>card.style.display=card.dataset.project.toLowerCase().includes(q)?'':'none');}
 if(e.target.matches('.range')){if(e.target.classList.contains('speed-range')){const label=e.target.closest('.field-block')?.querySelector('.field-title small');if(label)label.textContent=`${(Number(e.target.value)/100).toLocaleString('fa-IR',{minimumFractionDigits:1,maximumFractionDigits:1})}×`;}else{const m=Number(e.target.value);const value=document.querySelector('.duration-value');if(value)value.textContent=`${faDigits(m)} دقیقه`;const scenes=document.querySelector('.fact-scenes');if(scenes)scenes.textContent=`${faDigits(Math.max(3,Math.round(m*1.2)))} صحنه`;e.target.style.setProperty('--range',`${((m-1)/59)*100}%`);const cost=document.querySelector('.cost-text');if(cost)cost.textContent=`${faDigits(Math.round(m*12))} اعتبار`;}}
});
document.addEventListener('change',e=>{if(e.target.id==='reference-file'&&e.target.files?.[0]){const file=e.target.files[0];if(!file.type.startsWith('image/')){showToast('لطفاً یک تصویر انتخاب کن.');return}const url=URL.createObjectURL(file);const img=document.querySelector('.upload-preview');img.src=url;img.style.display='block';document.querySelector('.upload-label').textContent=file.name;document.querySelector('.upload-action').textContent='تغییر فایل';}});
document.addEventListener('dragover',e=>{if(e.target.closest('.upload-zone')){e.preventDefault();e.target.closest('.upload-zone').classList.add('dragover')}});
document.addEventListener('dragleave',e=>{if(e.target.closest('.upload-zone'))e.target.closest('.upload-zone').classList.remove('dragover')});
document.addEventListener('drop',e=>{const zone=e.target.closest('.upload-zone');if(zone){e.preventDefault();zone.classList.remove('dragover');const input=zone.querySelector('input');if(e.dataTransfer.files?.length){input.files=e.dataTransfer.files;input.dispatchEvent(new Event('change',{bubbles:true}))}}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')hideModal();if(e.key==='Enter'&&e.target.id==='library-search'){const q=e.target.value.toLowerCase();document.querySelectorAll('.library-grid .project-card').forEach(card=>card.style.display=card.dataset.project.toLowerCase().includes(q)?'':'none')}});
document.getElementById('modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')hideModal()});
render();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('/sw.js').catch(()=>{});
